name: Bouillancube
version: ${project.version}
main: fr.jaggernaute.bouillancube.Bouillancube
api-version: 1.16
authors: [ Jaggernaute ]
description: Private plugin-in for Bouillancube only
commands:
  gui:
    description: Ouvre le GUI1

  gui2:
    description: Ouvre le GUI2